const GET_USER = 'GET_USER'
const GET_LOGIN = 'GET_LOGIN'
const GET_SKIP = 'GET_SKIP'
const GET_REGIST = 'GET_REGIST'
const SET_REGIST = 'SET_REGIST'
const GET_SIGN = 'GET_SIGN'
const GET_CHANGEINFO = 'GET_CHANGEINFO'
const GET_USER_BYID = 'GET_USER_BYID'
const SET_LOGIN = "SET_LOGIN"
const GET_MANAGER = "GET_MANAGER"
const GET_ADDFRIEND = "GET_ADDFRIEND"
const SET_WEBSOCKET = "SET_WEBSOCKET"
const SET_REMINDDATAS = "SET_REMINDDATAS"
const SET_REMINDDATASG = "SET_REMINDDATASG"
//remindDatas

export default {
  GET_USER,
  GET_LOGIN,
  GET_SKIP,
  GET_REGIST,
  SET_REGIST,
  GET_SIGN,
  GET_CHANGEINFO,
  GET_USER_BYID,
  SET_LOGIN,
  GET_MANAGER,
  GET_ADDFRIEND,
  SET_WEBSOCKET,
  SET_REMINDDATAS,
  SET_REMINDDATASG
}
